# Auto-generated thermal config copy rules
# Generated by script in: device\google\zuma\customparts

PRODUCT_COPY_FILES += \
    device\google\zuma\customparts/CustomThermalProfiles/thermal_info_config_battery_hard_$(DEVICE_CODENAME).json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_battery_hard.json \
    device\google\zuma\customparts/CustomThermalProfiles/thermal_info_config_battery_medium_$(DEVICE_CODENAME).json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_battery_medium.json \
    device\google\zuma\customparts/CustomThermalProfiles/thermal_info_config_battery_off_$(DEVICE_CODENAME).json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_battery_off.json \
    device\google\zuma\customparts/CustomThermalProfiles/thermal_info_config_battery_soft_$(DEVICE_CODENAME).json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_battery_soft.json \
    device\google\zuma\customparts/CustomThermalProfiles/thermal_info_config_soc_hard_$(DEVICE_CODENAME).json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_soc_hard.json \
    device\google\zuma\customparts/CustomThermalProfiles/thermal_info_config_soc_hard_battery_hard_$(DEVICE_CODENAME).json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_soc_hard_battery_hard.json \
    device\google\zuma\customparts/CustomThermalProfiles/thermal_info_config_soc_hard_battery_medium_$(DEVICE_CODENAME).json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_soc_hard_battery_medium.json \
    device\google\zuma\customparts/CustomThermalProfiles/thermal_info_config_soc_hard_battery_off_$(DEVICE_CODENAME).json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_soc_hard_battery_off.json \
    device\google\zuma\customparts/CustomThermalProfiles/thermal_info_config_soc_hard_battery_soft_$(DEVICE_CODENAME).json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_soc_hard_battery_soft.json \
    device\google\zuma\customparts/CustomThermalProfiles/thermal_info_config_soc_medium_$(DEVICE_CODENAME).json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_soc_medium.json \
    device\google\zuma\customparts/CustomThermalProfiles/thermal_info_config_soc_medium_battery_hard_$(DEVICE_CODENAME).json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_soc_medium_battery_hard.json \
    device\google\zuma\customparts/CustomThermalProfiles/thermal_info_config_soc_medium_battery_medium_$(DEVICE_CODENAME).json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_soc_medium_battery_medium.json \
    device\google\zuma\customparts/CustomThermalProfiles/thermal_info_config_soc_medium_battery_off_$(DEVICE_CODENAME).json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_soc_medium_battery_off.json \
    device\google\zuma\customparts/CustomThermalProfiles/thermal_info_config_soc_medium_battery_soft_$(DEVICE_CODENAME).json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_soc_medium_battery_soft.json \
    device\google\zuma\customparts/CustomThermalProfiles/thermal_info_config_soc_off_$(DEVICE_CODENAME).json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_soc_off.json \
    device\google\zuma\customparts/CustomThermalProfiles/thermal_info_config_soc_off_battery_hard_$(DEVICE_CODENAME).json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_soc_off_battery_hard.json \
    device\google\zuma\customparts/CustomThermalProfiles/thermal_info_config_soc_off_battery_medium_$(DEVICE_CODENAME).json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_soc_off_battery_medium.json \
    device\google\zuma\customparts/CustomThermalProfiles/thermal_info_config_soc_off_battery_off_$(DEVICE_CODENAME).json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_soc_off_battery_off.json \
    device\google\zuma\customparts/CustomThermalProfiles/thermal_info_config_soc_off_battery_soft_$(DEVICE_CODENAME).json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_soc_off_battery_soft.json \
    device\google\zuma\customparts/CustomThermalProfiles/thermal_info_config_soc_soft_$(DEVICE_CODENAME).json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_soc_soft.json \
    device\google\zuma\customparts/CustomThermalProfiles/thermal_info_config_soc_soft_battery_hard_$(DEVICE_CODENAME).json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_soc_soft_battery_hard.json \
    device\google\zuma\customparts/CustomThermalProfiles/thermal_info_config_soc_soft_battery_medium_$(DEVICE_CODENAME).json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_soc_soft_battery_medium.json \
    device\google\zuma\customparts/CustomThermalProfiles/thermal_info_config_soc_soft_battery_off_$(DEVICE_CODENAME).json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_soc_soft_battery_off.json \
    device\google\zuma\customparts/CustomThermalProfiles/thermal_info_config_soc_soft_battery_soft_$(DEVICE_CODENAME).json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_soc_soft_battery_soft.json
